---
kind: pipeline
name: default
steps:
  - name: publish
    image: node:10
    environment:
      USERNAME:
        from_secret: EXPO_USERNAME
      PASSWORD:
        from_secret: EXPO_PASSWORD
    commands:
      - npm i -g expo-cli
      - npm ci
      - npx expo login -u $USERNAME -p $PASSWORD
      - npx expo publish --release-channel drone
